const sampleListings =[
  { "name": "Aarav Sharma", "rollNumber": "BT2021001", "email": "aarav.sharma@college.edu", "branch": "Computer Science Engineering", "year": 4 },
  { "name": "Priya Singh", "rollNumber": "BT2022002", "email": "priya.singh@college.edu", "branch": "Electronics and Communication Engineering", "year": 3 },
  { "name": "Rohan Mehta", "rollNumber": "BT2023003", "email": "rohan.mehta@college.edu", "branch": "Mechanical Engineering", "year": 2 },
  { "name": "Ananya Gupta", "rollNumber": "BT2024004", "email": "ananya.gupta@college.edu", "branch": "Civil Engineering", "year": 1 },
  { "name": "Vikram Patel", "rollNumber": "BT2021005", "email": "vikram.patel@college.edu", "branch": "Computer Science Engineering", "year": 4 },
  { "name": "Sneha Reddy", "rollNumber": "BT2022006", "email": "sneha.reddy@college.edu", "branch": "Information Technology", "year": 3 },
  { "name": "Arjun Nair", "rollNumber": "BT2023007", "email": "arjun.nair@college.edu", "branch": "Electrical Engineering", "year": 2 },
  { "name": "Pooja Verma", "rollNumber": "BT2024008", "email": "pooja.verma@college.edu", "branch": "Computer Science Engineering", "year": 1 },
  { "name": "Karan Joshi", "rollNumber": "BT2021009", "email": "karan.joshi@college.edu", "branch": "Mechanical Engineering", "year": 4 },
  { "name": "Divya Pillai", "rollNumber": "BT2022010", "email": "divya.pillai@college.edu", "branch": "Electronics and Communication Engineering", "year": 3 },
  { "name": "Rahul Kumar", "rollNumber": "BT2023011", "email": "rahul.kumar@college.edu", "branch": "Civil Engineering", "year": 2 },
  { "name": "Ishaan Chopra", "rollNumber": "BT2024012", "email": "ishaan.chopra@college.edu", "branch": "Information Technology", "year": 1 },
  { "name": "Meera Iyer", "rollNumber": "BT2021013", "email": "meera.iyer@college.edu", "branch": "Computer Science Engineering", "year": 4 },
  { "name": "Aditya Bhatt", "rollNumber": "BT2022014", "email": "aditya.bhatt@college.edu", "branch": "Electrical Engineering", "year": 3 },
  { "name": "Sanya Malhotra", "rollNumber": "BT2023015", "email": "sanya.malhotra@college.edu", "branch": "Mechanical Engineering", "year": 2 },
  { "name": "Nikhil Desai", "rollNumber": "BT2024016", "email": "nikhil.desai@college.edu", "branch": "Computer Science Engineering", "year": 1 },
  { "name": "Tanvi Saxena", "rollNumber": "BT2021017", "email": "tanvi.saxena@college.edu", "branch": "Electronics and Communication Engineering", "year": 4 },
  { "name": "Yash Kapoor", "rollNumber": "BT2022018", "email": "yash.kapoor@college.edu", "branch": "Civil Engineering", "year": 3 },
  { "name": "Riya Bose", "rollNumber": "BT2023019", "email": "riya.bose@college.edu", "branch": "Information Technology", "year": 2 },
  { "name": "Kabir Rao", "rollNumber": "BT2024020", "email": "kabir.rao@college.edu", "branch": "Computer Science Engineering", "year": 1 },
  { "name": "Nisha Tiwari", "rollNumber": "BT2021021", "email": "nisha.tiwari@college.edu", "branch": "Electrical Engineering", "year": 4 },
  { "name": "Siddharth Menon", "rollNumber": "BT2022022", "email": "siddharth.menon@college.edu", "branch": "Mechanical Engineering", "year": 3 },
  { "name": "Kavya Pandey", "rollNumber": "BT2023023", "email": "kavya.pandey@college.edu", "branch": "Computer Science Engineering", "year": 2 },
  { "name": "Arnav Mishra", "rollNumber": "BT2024024", "email": "arnav.mishra@college.edu", "branch": "Electronics and Communication Engineering", "year": 1 },
  { "name": "Shruti Ghosh", "rollNumber": "BT2021025", "email": "shruti.ghosh@college.edu", "branch": "Civil Engineering", "year": 4 },
  { "name": "Devansh Agarwal", "rollNumber": "BT2022026", "email": "devansh.agarwal@college.edu", "branch": "Information Technology", "year": 3 },
  { "name": "Palak Srivastava", "rollNumber": "BT2023027", "email": "palak.srivastava@college.edu", "branch": "Computer Science Engineering", "year": 2 },
  { "name": "Harsh Trivedi", "rollNumber": "BT2024028", "email": "harsh.trivedi@college.edu", "branch": "Electrical Engineering", "year": 1 },
  { "name": "Anjali Kulkarni", "rollNumber": "BT2021029", "email": "anjali.kulkarni@college.edu", "branch": "Mechanical Engineering", "year": 4 },
  { "name": "Vivek Chauhan", "rollNumber": "BT2022030", "email": "vivek.chauhan@college.edu", "branch": "Computer Science Engineering", "year": 3 },
  { "name": "Ritika Bansal", "rollNumber": "BT2023031", "email": "ritika.bansal@college.edu", "branch": "Electronics and Communication Engineering", "year": 2 },
  { "name": "Mohit Yadav", "rollNumber": "BT2024032", "email": "mohit.yadav@college.edu", "branch": "Civil Engineering", "year": 1 },
  { "name": "Swati Dubey", "rollNumber": "BT2021033", "email": "swati.dubey@college.edu", "branch": "Information Technology", "year": 4 },
  { "name": "Gaurav Shukla", "rollNumber": "BT2022034", "email": "gaurav.shukla@college.edu", "branch": "Computer Science Engineering", "year": 3 },
  { "name": "Bhavna Jain", "rollNumber": "BT2023035", "email": "bhavna.jain@college.edu", "branch": "Electrical Engineering", "year": 2 },
  { "name": "Parth Thakur", "rollNumber": "BT2024036", "email": "parth.thakur@college.edu", "branch": "Mechanical Engineering", "year": 1 },
  { "name": "Deepika Nambiar", "rollNumber": "BT2021037", "email": "deepika.nambiar@college.edu", "branch": "Computer Science Engineering", "year": 4 },
  { "name": "Sameer Wagh", "rollNumber": "BT2022038", "email": "sameer.wagh@college.edu", "branch": "Electronics and Communication Engineering", "year": 3 },
  { "name": "Kritika Rajan", "rollNumber": "BT2023039", "email": "kritika.rajan@college.edu", "branch": "Civil Engineering", "year": 2 },
  { "name": "Ayush Goel", "rollNumber": "BT2024040", "email": "ayush.goel@college.edu", "branch": "Information Technology", "year": 1 },
  { "name": "Neha Shetty", "rollNumber": "BT2021041", "email": "neha.shetty@college.edu", "branch": "Computer Science Engineering", "year": 4 },
  { "name": "Pranav Hegde", "rollNumber": "BT2022042", "email": "pranav.hegde@college.edu", "branch": "Electrical Engineering", "year": 3 },
  { "name": "Aditi Pawar", "rollNumber": "BT2023043", "email": "aditi.pawar@college.edu", "branch": "Mechanical Engineering", "year": 2 },
  { "name": "Rishabh Dixit", "rollNumber": "BT2024044", "email": "rishabh.dixit@college.edu", "branch": "Computer Science Engineering", "year": 1 },
  { "name": "Simran Oberoi", "rollNumber": "BT2021045", "email": "simran.oberoi@college.edu", "branch": "Electronics and Communication Engineering", "year": 4 },
  { "name": "Kunal Batra", "rollNumber": "BT2022046", "email": "kunal.batra@college.edu", "branch": "Civil Engineering", "year": 3 },
  { "name": "Aishwarya Deshpande", "rollNumber": "BT2023047", "email": "aishwarya.deshpande@college.edu", "branch": "Information Technology", "year": 2 },
  { "name": "Tarun Mathur", "rollNumber": "BT2024048", "email": "tarun.mathur@college.edu", "branch": "Computer Science Engineering", "year": 1 },
  { "name": "Prachi Goswami", "rollNumber": "BT2021049", "email": "prachi.goswami@college.edu", "branch": "Electrical Engineering", "year": 4 },
  { "name": "Akash Varma", "rollNumber": "BT2022050", "email": "akash.varma@college.edu", "branch": "Mechanical Engineering", "year": 3 },
  { "name": "Mansi Tripathi", "rollNumber": "BT2023051", "email": "mansi.tripathi@college.edu", "branch": "Computer Science Engineering", "year": 2 },
  { "name": "Dhruv Anand", "rollNumber": "BT2024052", "email": "dhruv.anand@college.edu", "branch": "Electronics and Communication Engineering", "year": 1 },
  { "name": "Rachna Pillai", "rollNumber": "BT2021053", "email": "rachna.pillai@college.edu", "branch": "Civil Engineering", "year": 4 },
  { "name": "Shivam Tomar", "rollNumber": "BT2022054", "email": "shivam.tomar@college.edu", "branch": "Information Technology", "year": 3 },
  { "name": "Komal Arora", "rollNumber": "BT2023055", "email": "komal.arora@college.edu", "branch": "Computer Science Engineering", "year": 2 },
  { "name": "Varun Khanna", "rollNumber": "BT2024056", "email": "varun.khanna@college.edu", "branch": "Electrical Engineering", "year": 1 },
  { "name": "Sunita Rathore", "rollNumber": "BT2021057", "email": "sunita.rathore@college.edu", "branch": "Mechanical Engineering", "year": 4 },
  { "name": "Abhinav Lal", "rollNumber": "BT2022058", "email": "abhinav.lal@college.edu", "branch": "Computer Science Engineering", "year": 3 },
  { "name": "Trisha Mukherjee", "rollNumber": "BT2023059", "email": "trisha.mukherjee@college.edu", "branch": "Electronics and Communication Engineering", "year": 2 },
  { "name": "Sumit Rawat", "rollNumber": "BT2024060", "email": "sumit.rawat@college.edu", "branch": "Civil Engineering", "year": 1 },
  { "name": "Nidhi Bajaj", "rollNumber": "BT2021061", "email": "nidhi.bajaj@college.edu", "branch": "Information Technology", "year": 4 },
  { "name": "Chirag Sethi", "rollNumber": "BT2022062", "email": "chirag.sethi@college.edu", "branch": "Computer Science Engineering", "year": 3 },
  { "name": "Vandana Rao", "rollNumber": "BT2023063", "email": "vandana.rao@college.edu", "branch": "Electrical Engineering", "year": 2 },
  { "name": "Rohit Pandya", "rollNumber": "BT2024064", "email": "rohit.pandya@college.edu", "branch": "Mechanical Engineering", "year": 1 },
  { "name": "Kriti Bhardwaj", "rollNumber": "BT2021065", "email": "kriti.bhardwaj@college.edu", "branch": "Computer Science Engineering", "year": 4 },
  { "name": "Nitin Khurana", "rollNumber": "BT2022066", "email": "nitin.khurana@college.edu", "branch": "Electronics and Communication Engineering", "year": 3 },
  { "name": "Sakshi Mittal", "rollNumber": "BT2023067", "email": "sakshi.mittal@college.edu", "branch": "Civil Engineering", "year": 2 },
  { "name": "Harshit Negi", "rollNumber": "BT2024068", "email": "harshit.negi@college.edu", "branch": "Information Technology", "year": 1 },
  { "name": "Preeti Soni", "rollNumber": "BT2021069", "email": "preeti.soni@college.edu", "branch": "Computer Science Engineering", "year": 4 },
  { "name": "Ankit Chawla", "rollNumber": "BT2022070", "email": "ankit.chawla@college.edu", "branch": "Electrical Engineering", "year": 3 },
  { "name": "Gayatri Menon", "rollNumber": "BT2023071", "email": "gayatri.menon@college.edu", "branch": "Mechanical Engineering", "year": 2 },
  { "name": "Saurabh Pal", "rollNumber": "BT2024072", "email": "saurabh.pal@college.edu", "branch": "Computer Science Engineering", "year": 1 },
  { "name": "Divyansh Rastogi", "rollNumber": "BT2021073", "email": "divyansh.rastogi@college.edu", "branch": "Electronics and Communication Engineering", "year": 4 },
  { "name": "Megha Choudhary", "rollNumber": "BT2022074", "email": "megha.choudhary@college.edu", "branch": "Civil Engineering", "year": 3 },
  { "name": "Aman Srivastav", "rollNumber": "BT2023075", "email": "aman.srivastav@college.edu", "branch": "Information Technology", "year": 2 },
  { "name": "Ishita Sengupta", "rollNumber": "BT2024076", "email": "ishita.sengupta@college.edu", "branch": "Computer Science Engineering", "year": 1 },
  { "name": "Puneet Ahuja", "rollNumber": "BT2021077", "email": "puneet.ahuja@college.edu", "branch": "Electrical Engineering", "year": 4 },
  { "name": "Taruna Gill", "rollNumber": "BT2022078", "email": "taruna.gill@college.edu", "branch": "Mechanical Engineering", "year": 3 },
  { "name": "Rajat Verma", "rollNumber": "BT2023079", "email": "rajat.verma@college.edu", "branch": "Computer Science Engineering", "year": 2 },
  { "name": "Lipika Das", "rollNumber": "BT2024080", "email": "lipika.das@college.edu", "branch": "Electronics and Communication Engineering", "year": 1 },
  { "name": "Shubham Tiwari", "rollNumber": "BT2021081", "email": "shubham.tiwari@college.edu", "branch": "Civil Engineering", "year": 4 },
  { "name": "Archana Nair", "rollNumber": "BT2022082", "email": "archana.nair@college.edu", "branch": "Information Technology", "year": 3 },
  { "name": "Vishal Dubey", "rollNumber": "BT2023083", "email": "vishal.dubey@college.edu", "branch": "Computer Science Engineering", "year": 2 },
  { "name": "Heena Malik", "rollNumber": "BT2024084", "email": "heena.malik@college.edu", "branch": "Electrical Engineering", "year": 1 },
  { "name": "Sourav Biswas", "rollNumber": "BT2021085", "email": "sourav.biswas@college.edu", "branch": "Mechanical Engineering", "year": 4 },
  { "name": "Namrata Joshi", "rollNumber": "BT2022086", "email": "namrata.joshi@college.edu", "branch": "Computer Science Engineering", "year": 3 },
  { "name": "Kartik Sharma", "rollNumber": "BT2023087", "email": "kartik.sharma@college.edu", "branch": "Electronics and Communication Engineering", "year": 2 },
  { "name": "Roshni Kapoor", "rollNumber": "BT2024088", "email": "roshni.kapoor@college.edu", "branch": "Civil Engineering", "year": 1 },
  { "name": "Amit Pandey", "rollNumber": "BT2021089", "email": "amit.pandey@college.edu", "branch": "Information Technology", "year": 4 },
  { "name": "Chandni Bhatt", "rollNumber": "BT2022090", "email": "chandni.bhatt@college.edu", "branch": "Computer Science Engineering", "year": 3 },
  { "name": "Lokesh Yadav", "rollNumber": "BT2023091", "email": "lokesh.yadav@college.edu", "branch": "Electrical Engineering", "year": 2 },
  { "name": "Poonam Desai", "rollNumber": "BT2024092", "email": "poonam.desai@college.edu", "branch": "Mechanical Engineering", "year": 1 },
  { "name": "Tushar Garg", "rollNumber": "BT2021093", "email": "tushar.garg@college.edu", "branch": "Computer Science Engineering", "year": 4 },
  { "name": "Swara Patil", "rollNumber": "BT2022094", "email": "swara.patil@college.edu", "branch": "Electronics and Communication Engineering", "year": 3 },
  { "name": "Hemant Shinde", "rollNumber": "BT2023095", "email": "hemant.shinde@college.edu", "branch": "Civil Engineering", "year": 2 },
  { "name": "Zoya Khan", "rollNumber": "BT2024096", "email": "zoya.khan@college.edu", "branch": "Information Technology", "year": 1 },
  { "name": "Rajeev Menon", "rollNumber": "BT2021097", "email": "rajeev.menon@college.edu", "branch": "Computer Science Engineering", "year": 4 },
  { "name": "Bindiya Chauhan", "rollNumber": "BT2022098", "email": "bindiya.chauhan@college.edu", "branch": "Electrical Engineering", "year": 3 },
  { "name": "Faraz Ahmed", "rollNumber": "BT2023099", "email": "faraz.ahmed@college.edu", "branch": "Mechanical Engineering", "year": 2 },
  { "name": "Lavanya Krishnan", "rollNumber": "BT2024100", "email": "lavanya.krishnan@college.edu", "branch": "Computer Science Engineering", "year": 1 }
]
module.exports = { data: sampleListings };